### ISSUE TITLE
전깃줄 ..

### ISSUE THREAD

**Issue by YEJIN325** [inh2613/CodingTest_Study#1]
정답 코드들 보면 리스트에 [A위치, B위치] append하고 정렬해서 풀던데

import sys
input = sys.stdin.readline

n = int(input())
lines = [0] * 500
dp = [1] * 500

for _ in range(n):
    start, end = map(int, input().split())
    lines[start-1] = end-1

for i in range(500):
    for j in range(i):
        if lines[i] > lines[j]:
            dp[i] = max(dp[i], dp[j]+1)

print(n-max(dp))

이렇게 lines 배열을 A 전봇대로 생각하고 B 전봇대 위치 값을 대입하면 자동으로 정렬이 되지 않나 ..? 엉엉 
왜 틀렸다고 할까.. 차이가 뭔데 !

**Comment by inh2613** [comment]
흠 근데 lines[start-1] = end-1 여기서 end-1은 왜한거야??  start-1은 인덱스 때문에 이해가 가는뎁

**Comment by inh2613** [comment]
그 중간에 0이 들어가서 안되는 거 같음!
요렇게 바꾸면 정답됨

```python
import sys
input = sys.stdin.readline

n = int(input())
lines = [0] * 500
dp = [1] * 500

for _ in range(n):
    start, end = map(int, input().split())
    lines[start-1] = end


while 0 in lines:
    lines.remove(0)
# print(lines)
for i in range(len(lines)):
    for j in range(i):
        if lines[i] > lines[j]:
            dp[i] = max(dp[i], dp[j]+1)
# print(dp)
print(n-max(dp))
```


중간에 0이 있는걸 다 지워야대

**Comment by YEJIN325** [comment]
아 대박 이해완료 .. 고마엉 ~~
